export enum ENoteLengths {
    MAX_LENGTH_NOTE_UNIQUE_NAME = 50,
    MIN_LENGTH_NOTE_UNIQUE_NAME = 1,
    LENGTH_OF_RAMDOM_UNIQUE_NAME = 6,
    MIN_LENGTH_NOTE_CONTENT = 1,
    MAX_LENGTH_PASSWORD = 50,
    MIN_LENGTH_PASSWORD = 4,
    MAX_LENGTH_NOTE_TITLE = 300,
    MAX_LENGTH_NOTE_AUTHOR = 100,
}
